Hard-coded the %appdata% paths
bennyboer/adobe-font-grabber pull request #2
Opened 2022-09-21 19:26 UTC by n8ventures

Hard-coded the data directory (`%appdata%` for Windows, `$HOME/Library/Application Support` for MacOS) to the program so you only need to put one argument which is specifically the save location of the fonts.

2022-09-21 20:02 UTC, bennyboer requested changes
Only found the one typo in the crate name, otherwise seems like a useful addition! Thanks for contributing!

2022-09-21 20:02 UTC, bennyboer commented on Cargo.toml
> +name = "adode-font-grabber"
I think you have a typo here 😄

2022-09-21 20:33 UTC, n8ventures commented on Cargo.toml
> +name = "adode-font-grabber"
My bad! But, thank you!

2022-09-21 20:35 UTC, n8ventures commented on Cargo.toml
> +name = "adode-font-grabber"
Fixed the typo!

2022-09-22 13:44 UTC, merged

2022-09-22 13:45 UTC, bennyboer commented
Thanks again! I'll provide a new release build for Windows the next few days 👍